---
  - name: Start VMs
    community.general.proxmox_kvm:
      api_token_id: "{{ vm_api_token_id }}"
      api_password: "{{ vm_api_token_secret }}"
      api_token_secret: "{{ vm_api_token_secret }}"
      api_host: "{{ vm_api_host }}"
      api_user: "{{vm_api_user}}"
      name: "{{ item.vm_name }}"
      node: "{{ vm_node }}"
      state: started
    with_items: "{{ vms }}"
