---
  - name: Start VMs
    community.general.proxmox_kvm:
      api_token_id: "{{ vm_api_token_id }}"
      api_password: "{{ vm_api_token_secret }}"
      api_token_secret: "{{ vm_api_token_secret }}"
      api_host: "{{ vm_api_host }}"
      api_user: "{{vm_api_user}}"
      name: "{{ item.vm_name }}"
      node: "{{ vm_node }}"
      state: started
    with_items: "{{ vms }}"

  # Pause is need cause i don't know but you cant sign in via ssh some secounds after creating vm so please wait
  - name: Pause for 3 minutes to refresh vms with cloudinit setup
    pause:
      minutes: 3
      prompt: "Please dont skip this task, Pause is need cause i don't know but you cant sign in via ssh and console  some secounds after creating vm so please wait one task (snapshot) left"
    when: addvm.changed

  - name: make snapshot (after pause)
    community.general.proxmox_snap:
      api_user: "{{vm_api_user}}"
      api_password: "{{ vm_api_password }}"
      api_host: "{{ vm_api_host }}"
      vmid: "{{ item.vmid }}"
      state: present
      snapname: auto_snap_after_create
    with_items: "{{ addvm.results}}"
    when: item.changed
